<?php
$doc_id = $_SESSION['doc_id'];
$doc_number = $_SESSION['doc_number'];
$ret = "SELECT * FROM his_docs WHERE doc_id = ? AND doc_number = ?";
$stmt = $mysqli->prepare($ret);
$stmt->bind_param('is', $doc_id, $doc_number);
$stmt->execute();
$res = $stmt->get_result();
while($row = $res->fetch_object()) {
?>
<!-- Top Navigation - Hardened with hospa_ classes -->
<header class="hospa__topnav">
    <div class="hospa__topnav-left">
        <!-- Hamburger menu will be auto-generated by sidebar.js if not present -->
    </div>

    <!-- <div class="hospa__topnav-search">
        <input type="text" placeholder="Search...">
        <button><i class="fe-search"></i></button>
    </div> -->

    <div class="hospa__topnav-right">
        <button class="hospa__header-action">
            <i class="fe-bell"></i>
            <span class="hospa__badge">3</span>
        </button>
        
        <!-- Create New Dropdown -->
        <div class="dropdown" style="display:inline-block;">
            <button class="hospa__header-action dropdown-toggle" data-toggle="dropdown" style="font-size:0.9rem; font-weight:500;">
                Create <i class="mdi mdi-chevron-down"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="register-patient" class="dropdown-item">
                    <i class="fe-activity mr-1"></i> Patient
                </a>
                <a href="lab-report" class="dropdown-item">
                    <i class="fe-hard-drive mr-1"></i> Lab Report
                </a>
                <div class="dropdown-divider"></div>
                <a href="add-pharmaceuticals" class="dropdown-item">
                    <i class="mdi mdi-pill mr-1"></i> Pharmaceutical
                </a>
            </div>
        </div>
        
        <!-- User Profile -->
        <div class="hospa__user-profile dropdown">
            <div class="hospa__user-avatar">
                <img src="assets/images/users/<?php echo $row->doc_dpic; ?>" alt="Profile">
            </div>
            <span class="hospa__user-name dropdown-toggle" data-toggle="dropdown">
                <?php echo $row->doc_fname; ?> <?php echo $row->doc_lname; ?> 
                <i class="mdi mdi-chevron-down"></i>
            </span>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown">
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>
                <a href="update-account" class="dropdown-item notify-item">
                    <i class="fas fa-user-tag"></i> Update Account
                </a>
                <div class="dropdown-divider"></div>
                <a href="logout-partial" class="dropdown-item notify-item">
                    <i class="fe-log-out"></i> Logout
                </a>
            </div>
        </div>
    </div>
</header>
<?php } ?>